# inherit_from: .rubocop-todo.yml
Rails:
  Enabled: true
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - bin/**
    - app/controllers/application_controller.rb
    - app/helpers/application_helper.rb
    - Rakefile
    - spec/spec_helper.rb